[package]
name = "sdl2-test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "*"

[dependencies.sdl2]
sdl2 = "0.34.3"
features = ["ttf","image"]

